name: NetBox
version: "0.1.0"
slug: netbox
description: A Home Assistant add-on to run NetBox
startup: services
boot: auto
homeassistant_api: false
init: false
ingress: true
arch:
  - amd64
  - aarch64
ports:
  8000/tcp: 8000
options:
  admin_username: admin
  admin_password: password
  db_host: netbox_db
  db_user: netbox
  db_password: password
  db_name: netbox
  db_wait_debug: false
schema:
  admin_username: str
  admin_password: str
  db_host: str
  db_user: str
  db_password: str
  db_name: str
  db_wait_debug: bool
environment:
  DB_HOST: "!secret db_host"
  DB_NAME: "!secret db_name"
  DB_USER: "!secret db_user"
  DB_PASSWORD: "!secret db_password"
  SUPERUSER_NAME: "!secret admin_username"
  SUPERUSER_PASSWORD: "!secret admin_password"
  DB_WAIT_DEBUG: "!secret db_wait_debug"
