name: "SoloPlay Server"
description: "SoloPlay server-applikation med PostgreSQL support, Tilgå website via http://<ha-IP>:6968 eller en anden port hvis du har ændret det i config"
version: "1.0.2"
slug: "soloplay"
init: false

# Sidepanel og Ingress konfiguration
ingress: false
ingress_port: 6968
panel_title: "SoloPlay"
panel_icon: "mdi:controller"

arch:
  - amd64
  - aarch64
ports:
  6968/tcp: 6968
ports_description:
  6968/tcp: "SoloPlay Web interface"
options:
  app_token: "Skift_Dette_Token_Til_Noget_Langt_Over_50_Tegn"
  enable_migration: true
  db_host: "core-postgressql" # eller IP på din Postgres server
  db_port: 5432
  db_name: "Soloplay"
  db_user: "app"
  db_password: "postgres-dev-password"
schema:
  app_token: str
  enable_migration: bool
  db_host: str
  db_port: int
  db_name: str
  db_user: str
  db_password: str
